---
- name: Install and configure Docker on VMs
  hosts: cloud_vms     # Target group from inventory file
  become: true         # Ensure the tasks run with elevated privileges
  gather_facts: false

  tasks:

    - name: Update apt package index
      ansible.builtin.apt:
        update_cache: yes

    - name: Install Docker
      ansible.builtin.apt:
        name: docker.io
        state: present

    - name: Add current user to the docker group
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        groups: docker
        append: yes

    - name: Start and enable Docker service
      ansible.builtin.systemd:
        name: docker
        enabled: true
        state: started

    - name: Open port 2375 for Docker (if required for remote API access)
      ansible.builtin.firewalld:
        port: 2375/tcp
        permanent: yes
        state: enabled

    - name: Open port 2181 for Zookeeper communication
      ansible.builtin.firewalld:
        port: 2181/tcp
        permanent: yes
        state: enabled

    - name: Open port 9092 for Kafka broker
      ansible.builtin.firewalld:
        port: 9092/tcp
        permanent: yes
        state: enabled

    - name: Reload firewalld to apply new rules
      ansible.builtin.command:
        cmd: firewall-cmd --reload
      changed_when: false
