---
- name: "Copy Kafka tarball to the VM"
  copy:
    src: "/tmp/kafka_2.13-3.8.0.tgz"
    dest: "/tmp/kafka_2.13-3.8.0.tgz"

- name: "Extract Kafka"
  unarchive:
    src: "/tmp/kafka_2.13-3.8.0.tgz"
    dest: "/opt/"
    remote_src: yes

- name: "Create Kafka user"
  user:
    name: kafka
    state: present

- name: "Set permissions for Kafka directory"
  file:
    path: /opt/kafka_2.13-3.8.0
    owner: kafka
    group: kafka
    recurse: yes
