---
- name: Install required pip packages
  hosts: all
  become: true
  tasks:
    - name: Ensure pip is installed
      ansible.builtin.package:
        name: python3-pip
        state: present

    - name: Upgrade pip to the latest version
      ansible.builtin.pip:
        name: pip
        state: latest

    - name: Install required Python packages
      ansible.builtin.pip:
        name:
          - ansible
          - kafka-python
          - requests  # Needed for HTTP requests (e.g., in the producer or consumer)
          - Flask     # If you're using Flask for the ML model server
          - numpy     # Needed for data processing and mock data generation
          - Pillow    # For image processing, used in the IoT producer
          - boto3     # Optional, if you plan to interact with AWS or other cloud services
        state: latest
