---
- name: Update apt repository cache
  ansible.builtin.apt:
    update_cache: true

- name: Install required apt packages
  ansible.builtin.apt:
    name:
      - python3-pip
      - build-essential
    state: present
