---
- name: Ensure firewalld is installed and running
  ansible.builtin.yum:
    name: firewalld
    state: present

- name: Start and enable firewalld
  ansible.builtin.systemd:
    name: firewalld
    enabled: true
    state: started

- name: Open required Kafka ports
  ansible.posix.firewalld:
    port: "{{ item }}"
    permanent: true
    state: enabled
  loop:
    - 9092/tcp
    - 2181/tcp

- name: Reload firewalld
  ansible.builtin.command:
    cmd: firewall-cmd --reload
  changed_when: false
