---
- name: Check if all required variables are defined
  ansible.builtin.fail:
    msg: "Required variable {{ item }} is not defined."
  when: item is not defined
  loop:
    - local_user
    - cloud_user
    - ansible_user
    - ansible_ssh_private_key_file
    - ansible_ssh_common_args
