---
- name: "Update apt package index"
  apt:
    update_cache: yes

- name: "Install required APT packages"
  apt:
    name:
      - python3
      - python3-pip
      - unzip
      - curl
    state: present
